[profile.default]
libs = ["lib"]
out = "out"
src = "src"

remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts", "@solmate/=lib/solmate/"]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
rpc_endpoints = {mainnet = "https://rpc.ankr.com/eth", optimism = "https://opt-mainnet.g.alchemy.com/v2/demo", fantom = "https://rpc.ankr.com/fantom", arbitrum = "https://rpc.ankr.com/arbitrum", bsc = "https://rpc.ankr.com/bsc", moonriver = "https://moonriver.public.blastapi.io", gnosis = "https://rpc.ankr.com/gnosis", Avalanche = "https://rpc.ankr.com/avalanche", polygon = "https://rpc.ankr.com/polygon", celo = "https://rpc.ankr.com/celo", Base = "https://developer-access-mainnet.base.org"}

# See more config options https://github.com/gakonst/foundry/tree/master/config

[fmt]
bracket_spacing = false
func_attrs_with_params_multiline = false
ignore = []
int_types = "long"
line_length = 120
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
single_line_statement_blocks = 'preserve'
tab_width = 4
variable_override_spacing = true
wrap_comments = false
